version: "3"
services:
  mariadb:
    build: 
      context: ./mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    container_name: mariadb
  moodle:
    build: 
      context: ./moodle
      args:
        - EXTRA_LOCALES=ru_RU.UTF-8 UTF-8,
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
      - MOODLE_LANG=ru
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    links:
      - mariadb
    container_name: moodle
  jobeinabox:
    build:
      context: ./jobeinabox
      args:
      - TZ=Europe/Moscow
    container_name: jobeinabox
    ports:
      - '4000:80'
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
