apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobe
  template:
    metadata:
      labels:
        app: jobe
    spec:
      containers:
        - name: jobe
          image: trampgeek/jobeinabox
          env:
            - name: TZ
              value: Europe/Moscow
          ports:
            - containerPort: 80
              hostPort: 4000
              protocol: TCP
