apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:11.1
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MARIADB_USER
              value: bn_moodle
            - name: MARIADB_DATABASE
              value: bitnami_moodle
            - name: MARIADB_CHARACTER_SET
              value: utf8mb4
            - name: MARIADB_COLLATE
              value: utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /bitnami/mariadb
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
