apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
        - name: moodle
          image: bitnami/moodle:4.1
          env:
            - name: MOODLE_DATABASE_HOST
              value: mariadb-service
            - name: MOODLE_DATABASE_PORT_NUMBER
              value: "3306"
            - name: MOODLE_DATABASE_USER
              value: bn_moodle
            - name: MOODLE_DATABASE_NAME
              value: bitnami_moodle
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: BITNAMI_DEBUG
              value: "true"
            - name: MOODLE_LANG
              value: ru
          ports:
            - containerPort: 8080
              hostPort: 80
              protocol: TCP
            - containerPort: 8443
              hostPort: 443
              protocol: TCP
          volumeMounts:
            - name: moodle-data
              mountPath: /bitnami/moodle
            - name: moodledata-data
              mountPath: /bitnami/moodledata
      volumes:
        - name: moodle-data
          persistentVolumeClaim:
            claimName: moodle-data-pvc
        - name: moodledata-data
          persistentVolumeClaim:
            claimName: moodledata-data-pvc
