deployment:
  moodle:
    replicas: 1
    image: bitnami/moodle:4.1
  jobe:
    replicas: 1
    image: trampgeek/jobeinabox
  db:
    replicas: 1 
    image: bitnami/mariadb:11.1

pvc:
  db:
    size: 10Gi
  moodle:
    size: 5Gi
  moodleData:
    size: 5Gi



