apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.db.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.moodle.size }}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodledata-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.moodleData.size }}