apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobe
  template:
    metadata:
      labels:
        app: jobe
    spec:
      containers:
        - name: jobe
          image: trampgeek/jobeinabox
          env:
            - name: TZ
              value: Europe/Moscow
          ports:
            - containerPort: 80
              hostPort: 4000
              protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:11.1
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MARIADB_USER
              value: bn_moodle
            - name: MARIADB_DATABASE
              value: bitnami_moodle
            - name: MARIADB_CHARACTER_SET
              value: utf8mb4
            - name: MARIADB_COLLATE
              value: utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /bitnami/mariadb
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
        - name: moodle
          image: bitnami/moodle:4.1
          env:
            - name: MOODLE_DATABASE_HOST
              value: mariadb-service
            - name: MOODLE_DATABASE_PORT_NUMBER
              value: "3306"
            - name: MOODLE_DATABASE_USER
              value: bn_moodle
            - name: MOODLE_DATABASE_NAME
              value: bitnami_moodle
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: BITNAMI_DEBUG
              value: "true"
            - name: MOODLE_LANG
              value: ru
          ports:
            - containerPort: 8080
              hostPort: 80
              protocol: TCP
            - containerPort: 8443
              hostPort: 443
              protocol: TCP
          volumeMounts:
            - name: moodle-data
              mountPath: /bitnami/moodle
            - name: moodledata-data
              mountPath: /bitnami/moodledata
      volumes:
        - name: moodle-data
          persistentVolumeClaim:
            claimName: moodle-data-pvc
        - name: moodledata-data
          persistentVolumeClaim:
            claimName: moodledata-data-pvc

